-- Migration: 20260308192204_cis_proposals_outcomes_calibration
-- Applied: backfilled from supabase_migrations.schema_migrations 2026-04-17
-- Name: cis_proposals_outcomes_calibration


-- ── TABLE 9: PROPOSALS ───────────────────────────────────────
-- AI-generated campaign proposals awaiting CEO approval
CREATE TABLE cis.proposals (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  proposal_ref          TEXT NOT NULL UNIQUE,
  action_type           TEXT NOT NULL CHECK (action_type IN (
                          'new_campaign', 'new_ad_group', 'new_keywords',
                          'pause_campaign', 'pause_keyword', 'adjust_bid',
                          'adjust_budget', 'new_ad_copy', 'add_negative_keywords',
                          'new_linkedin_campaign', 'adjust_targeting'
                        )),
  platform              TEXT NOT NULL CHECK (platform IN ('google', 'linkedin', 'both')),
  status                TEXT NOT NULL DEFAULT 'pending' CHECK (status IN (
                          'pending', 'approved', 'rejected', 'deployed', 'failed'
                        )),
  -- Empirical basis
  data_basis            JSONB NOT NULL,
  data_basis_summary    TEXT NOT NULL,
  -- Proposed action detail
  proposed_payload      JSONB NOT NULL,
  proposed_copy         JSONB,
  proposed_targeting    JSONB,
  proposed_budget_gbp   NUMERIC(10,2),
  proposed_bid_gbp      NUMERIC(10,4),
  -- Projections
  projected_impressions BIGINT,
  projected_clicks      BIGINT,
  projected_conversions NUMERIC(10,2),
  projected_cpa_gbp     NUMERIC(10,2),
  confidence_score      SMALLINT NOT NULL CHECK (confidence_score BETWEEN 0 AND 100),
  -- CEO decision
  ceo_decision_at       TIMESTAMPTZ,
  ceo_notes             TEXT,
  -- Deployment
  deployed_at           TIMESTAMPTZ,
  deployment_response   JSONB,
  -- Generated by
  generated_at          TIMESTAMPTZ DEFAULT now(),
  claude_model          TEXT,
  prompt_version        TEXT
);

-- ── TABLE 10: PROPOSAL OUTCOMES ──────────────────────────────
-- Tracks actual vs projected performance per deployed proposal
CREATE TABLE cis.proposal_outcomes (
  id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  proposal_id             UUID NOT NULL REFERENCES cis.proposals(id) ON DELETE CASCADE,
  measurement_window_days SMALLINT NOT NULL DEFAULT 14,
  measured_at             TIMESTAMPTZ DEFAULT now(),
  actual_impressions      BIGINT,
  actual_clicks           BIGINT,
  actual_conversions      NUMERIC(10,2),
  actual_cpa_gbp          NUMERIC(10,2),
  actual_cost_gbp         NUMERIC(10,2),
  -- Variance vs projection
  impressions_variance_pct NUMERIC(8,2),
  clicks_variance_pct      NUMERIC(8,2),
  conversions_variance_pct NUMERIC(8,2),
  cpa_variance_pct         NUMERIC(8,2),
  outcome_notes           TEXT,
  created_at              TIMESTAMPTZ DEFAULT now()
);

-- ── TABLE 11: MODEL CALIBRATION ──────────────────────────────
-- System accuracy log — powers self-calibration of confidence scores
CREATE TABLE cis.model_calibration (
  id                        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  calibration_date          DATE NOT NULL,
  proposals_evaluated       SMALLINT NOT NULL,
  mean_abs_error_clicks     NUMERIC(8,2),
  mean_abs_error_conversions NUMERIC(8,2),
  mean_abs_error_cpa        NUMERIC(8,2),
  confidence_accuracy_score NUMERIC(5,2),
  calibration_notes         TEXT,
  recommended_confidence_adj NUMERIC(5,2),
  created_at                TIMESTAMPTZ DEFAULT now()
);

-- ── INDEXES ──────────────────────────────────────────────────
CREATE INDEX idx_cis_performance_daily_campaign_date 
  ON cis.performance_daily(campaign_id, snapshot_date DESC);

CREATE INDEX idx_cis_search_terms_campaign_date 
  ON cis.search_terms(campaign_id, recorded_date DESC);

CREATE INDEX idx_cis_conversions_attributed 
  ON cis.conversions(attributed_at DESC);

CREATE INDEX idx_cis_conversions_campaign 
  ON cis.conversions(campaign_id);

CREATE INDEX idx_cis_proposals_status 
  ON cis.proposals(status, generated_at DESC);

CREATE INDEX idx_cis_audience_campaign_date 
  ON cis.audience_segments(campaign_id, snapshot_date DESC);

CREATE INDEX idx_cis_keywords_campaign 
  ON cis.keywords(campaign_id, status);

